function val = bspline_2nd_expectation(knots,coef_matrix,thetas,spline_number1,...
    spline_number2)
    [~,bspline_dim] = size(coef_matrix);
    fun = @(x)(get_bspline_value(x,knots,coef_matrix,spline_number1).*...
        logspline_density(x, knots,coef_matrix,thetas).*...
        get_bspline_value(x,knots,coef_matrix,spline_number2));
    val = integral(fun, knots(min(spline_number1,spline_number2)), ...
        knots(max(spline_number1,spline_number2)+bspline_dim));
end